# Generated by Django 6.0.4 on 2026-06-02 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admins', '0002_customercredit_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='products/'),
        ),
    ]
