# Generated by Django 6.0.5 on 2026-06-02 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admins', '0003_product_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='tax_percentage',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Tax percentage (e.g., 18 for 18%)', max_digits=5, null=True),
        ),
    ]
