# Generated by Django 6.0.4 on 2026-06-03 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop_admins', '0004_product_tax_percentage'),
    ]

    operations = [
        migrations.AddField(
            model_name='billitem',
            name='unit',
            field=models.CharField(default='piece', help_text='Unit of measurement', max_length=20),
        ),
        migrations.AddField(
            model_name='product',
            name='unit',
            field=models.CharField(choices=[('piece', 'Piece'), ('kg', 'Kilogram (kg)'), ('liter', 'Liter (L)'), ('gram', 'Gram (g)'), ('ml', 'Milliliter (ml)'), ('pack', 'Pack'), ('box', 'Box')], default='piece', help_text='Unit of measurement', max_length=20),
        ),
        migrations.AlterField(
            model_name='billitem',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity (supports decimals for kg/liter)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='product',
            name='stock',
            field=models.DecimalField(decimal_places=3, default=0, help_text='Stock quantity (supports decimals for kg/liter)', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stocklog',
            name='quantity',
            field=models.DecimalField(decimal_places=3, help_text='Quantity (supports decimals for kg/liter)', max_digits=10),
        ),
    ]
